Update release_channel.md to clarify behavior of per-action approvals
prodvana/terraform-provider-prodvana pull request #32
Opened 2023-09-05 22:55 UTC by naphatkrit

2023-09-05 22:55 UTC, anupcshan approved these changes

2023-09-05 23:44 UTC, betamike requested changes

2023-09-05 23:44 UTC, betamike commented on docs/resources/release_channel.md
> +- `every_action` (Boolean) whether this approval is required for every convergence action, or just the first. This only works for runtime extensions and Terraform runners. Setting this field to true
This documentation is generated from the code here:
https://github.com/prodvana/terraform-provider-prodvana/blob/b2fe48859e0ec6a4f3e7a73488e19a3957714227/internal/provider/release_channel_resource.go#L394

Could you change it there and run `go generate` ?

2023-09-07 00:27 UTC, betamike commented
I took care of this in #34

2023-09-07 00:27 UTC, closed without merging

2023-09-07 00:38 UTC, naphatkrit commented
Ah sorry, thank you